language: python
python: 3.8
cache: pip
env:
  global:
    - REPO_NAME="${PWD##*/}"
    - IMAGE_NAME="${REPO_NAME}-${TRAVIS_BRANCH}"
    - AWS_PROFILE="ci-role"
#    - AWS_ROLE_ARN="${AwsCfServiceRoleArn}"
#    - AWS_ACCESS_KEY_ID="${AwsTravisAccessKey}"
#    - AWS_SECRET_ACCESS_KEY="${AwsTravisSecretAccessKey}"
    - AWS_REGION="us-east-1"
    - AWS_SOURCE_IMAGE_PATH="/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
install:
  # install packer
#  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
#  - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
#  - sudo apt-get update && sudo apt-get install packer
  # install awscli v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip && sudo ./aws/install
  # install other tools
#  - pip install pre-commit travis-wait-improved ansible
before_script:
  - mkdir -p ~/.aws
  - echo -e "[profile ${AWS_PROFILE}]\nregion=${AWS_REGION}\nsource_profile=ci-user\nrole_arn=${AwsCfServiceRoleArn}" > ~/.aws/config
  - echo -e "[ci-user]\nregion=${AWS_REGION}\naws_access_key_id=${AwsTravisAccessKey}\naws_secret_access_key=${AwsTravisSecretAccessKey}" > ~/.aws/credentials
stages:
#  - name: validate
  - name: deploy-branch
    if: type = push AND branch = master
  - name: deploy-tag
    if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]
jobs:
  include:
#    - stage: validate
#      script:
#        - pre-commit run --all-files
#        - pushd src
#        - packer validate -var ImageName=${IMAGE_NAME} -var SourceImage="some_aws_image_path" template.json
    - stage: deploy-branch
      script:
        - cat ~/.aws/config
#        - echo "${AWS_ROLE_ARN}"
        - echo "${REPO_NAME}"
        - echo "${IMAGE_NAME}"
        - echo "${AWS_PROFILE}"
        - echo "${AWS_REGION}"
        - echo "${AWS_SOURCE_IMAGE_PATH}"
        - aws --profile ${AWS_PROFILE} --region ${AWS_REGION} ssm get-parameters --names ${AWS_SOURCE_IMAGE_PATH} --query 'Parameters[0].[Value]' --output text
        - export LATEST_AMI=$(aws --profile ${AWS_PROFILE} --region ${AWS_REGION} ssm get-parameters --names ${AWS_SOURCE_IMAGE_PATH} --query 'Parameters[0].[Value]' --output text)
        - echo "${LATEST_AMI}"
#        - pushd src
#        - travis-wait-improved --timeout 45m packer build -force -var AwsProfile=${AWS_PROFILE} -var ImageName=${IMAGE_NAME} -var SourceImage=${LATEST_AMI} template.json
#    - stage: deploy-tag
#      script:
#        - export LATEST_AMI=$(aws ssm get-parameters --profile ${AWS_PROFILE} --region ${AWS_REGION} --names ${AWS_SOURCE_IMAGE_PATH} --query 'Parameters[0].[Value]' --output text)
#        - pushd src
#        - travis-wait-improved --timeout 45m packer build -force -var AwsProfile=${AWS_PROFILE} -var ImageName=${IMAGE_NAME} -var SourceImage=${LATEST_AMI} template.json
