- hosts: all
  become: yes

  tasks:
    # - name: Get base playbook
    #   get_url: url=https://raw.githubusercontent.com/Sage-Bionetworks/packer-base-ubuntu-bionic/v1.0.0/src/playbook.yaml dest={{ playbook_dir }}/sagebio-base-ubuntu-bionic-v1.0.0.yaml

    # - include_tasks: sagebio-base-ubuntu-bionic-v1.0.0.yaml

    - name: Add the CRAN apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E298A3A825C0D65DFD57CBB651716619E084DAB9

    - name: Add R-Project apt repository
      shell: "aptdcon --add-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran40/' && aptdcon --refresh"

    - name: install packages
      shell: "yes | aptdcon --hide-terminal --install 'zlib1g-dev libclang-dev libssl-dev libffi-dev libcurl4-openssl-dev libapparmor1 libssl1.0.0 r-base r-base-dev libxml2-dev'"

    # Install R packages
    - name: Install devtools
      shell: "R -e \"install.packages('devtools')\""

    - name: Install synapser
      shell: "R -e \"install.packages('synapser', repos=c('http://ran.synapse.org', 'http://cran.fhcrc.org'))\""

    - name: Install tidyverse
      shell: "R -e \"install.packages('tidyverse')\""

    - name: Install shiny
      shell: "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""

    # Install Shiny server
    - name: Download Shiny Server
      get_url: url=https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.13.944-amd64.deb dest=/tmp/shiny.deb

    - name: Install Shiny Server
      command: gdebi shiny-server-1.5.13.944-amd64.deb
